/*CORMVH Ordenes de compra
DECLARE @CODEMP VARCHAR (6), @CODTRA VARCHAR (12), @NROLOT VARCHAR (3)
SET @CODTRA = 'KT319'
SET @CODEMP = 'L2001'
*/
SELECT CORMVH_NROFOR FLD001,
	   CORMVI_DEPOSI FLD002,
	   STTDEH_DESCRP FLD003,
	   STMPDH_DESCRP FLD004,
	   RTRIM(CONVERT(VARCHAR,CORMVI_TIPORI))+RTRIM(CONVERT(VARCHAR,CORMVI_ARTORI)) FLD005,
	   Sum(CORMVI_CANTID) FLD006,
	   @NROLOT FLD007,
	   CORMVH_FCHVEN FLD008,
	   SPACE(1) FLD009,
	   SPACE(1) FLD010,
	   SPACE(1) FLD011,
	   SPACE(1) FLD012,
	   SPACE(1) FLD013,
	   (CONVERT(VARCHAR,CORMVH_NROCTA))+CONVERT(VARCHAR,1) FLD099 /*Orden de Registro*/
FROM  CORMVH
INNER JOIN COTCIH ON COTCIH_CIRCOM = CORMVH_CIRCOM AND  COTCIH_CIRAPL = CORMVH_CIRAPL 
INNER JOIN STTDEH ON STTDEH_DEPOSI  = CORMVH_DEPOSI 
INNER JOIN CORMVI ON CORMVI_CODEMP = @CODEMP and CORMVI_MODFOR = CORMVH_MODFOR and CORMVI_CODFOR = CORMVH_CODFOR
AND CORMVI_NROFOR = CORMVH_NROFOR AND CORMVI_TIPCPT = 'A'
INNER JOIN STMPDH ON STMPDH_TIPPRO = CORMVI_TIPORI AND STMPDH_ARTCOD = CORMVI_ARTORI


WHERE
ISNULL(USR_CORMVH_ENVTAS,'N') = 'N' AND 
ISNULL(USR_COTCIH_ENVIAR,'N') = 'S' AND
EXISTS(select * from STTTPH WHERE STTTPH_TIPPRO = CORMVI_TIPORI AND  STTTPH_STOCKS = 'S') AND 
CORMVH_CODEMP = @CODEMP
group by CORMVH_NROFOR,
		CORMVI_DEPOSI,
		STTDEH_DESCRP,
		STMPDH_DESCRP,
		CORMVI_CANTID,
		CORMVI.CORMVI_TIPORI,
		CORMVI.CORMVI_ARTORI,
		CORMVH.CORMVH_FCHVEN,
		CORMVH.CORMVH_NROCTA
having Sum(CORMVI_CANTID)>0